services:
  ros2_scara:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_scara_dev
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - ./ros2_ws:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
    working_dir: /ros2_ws
    stdin_open: true
    tty: true
    devices:
      - /dev/dri
    networks:
      rosnet:
        ipv4_address: 172.21.176.18
    ports:
      - "11311:11311" # solo si lo necesitas, ROS 2 usa DDS
networks:
  rosnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
